# Generated by Django 5.2.1 on 2025-05-25 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_purchase'),
        ('users', '0002_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'ticket')},
        ),
    ]
